let newdata = []; // to show data when search new data array
let accdata = []; // to sore account info i use this data array

// all data

let data = [
    {
        name: "GameGuard",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelPirate",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGuru",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ControllerChamp",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "QuestMaster",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ArcadeAddict",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelWarrior",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ConsoleKing",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "JoystickJockey",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RetroGamer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LANPartyPro",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameOn",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VirtualVigilante",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsLegend",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamePadPro",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DungeonMaster",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LevelUpLion",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameWizard",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelNinja",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ConsoleCommander",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsWarrior",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RPGHero",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGenius",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DigitalDuelist",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VRVirtuoso",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameMaverick",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamerGeek",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "CyberWarrior",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameChanger",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelPioneer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "QuestHunter",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "JoystickJester",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RetroHero",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LANPartyLegend",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGoddess",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VirtualValkyrie",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsProphet",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamePadPioneer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DungeonDominator",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LevelUpLynx",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameSorcerer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelPhantom",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ConsoleCrusader",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsChampion",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RPGSorceress",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameWhiz",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DigitalDaredevil",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VRVanguard",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameMastermind",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamerGoddess",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "CyberCrusader",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameChampion",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelPathfinder",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "QuestSeeker",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "JoystickJoker",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RetroRebel",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LANPartyLion",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGuardian",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VirtualVoyager",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsOracle",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamePadProdigy",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DungeonDelver",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LevelUpLark",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameSage",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelProdigy",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ConsoleChieftain",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsHeroine",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RPGAdventurer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameSavant",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DigitalDynamo",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VRVirtuosa",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameStrategist",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamerGladiator",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "CyberSorcerer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameVictor",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelExplorer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "QuestConqueror",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "JoystickJuggler",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RetroRover",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LANPartyLancer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGuard",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VirtualVoyager",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsSage",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamePadProdigy",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DungeonDelver",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LevelUpLark",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameSorceress",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelProdigy",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "ConsoleChampion",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "eSportsHero",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RPGAdventurer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameStrategist",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "DigitalDynamo",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "VRVirtuoso",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameStrategist",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GamerGladiator",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "CyberSorcerer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameVictor",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "PixelExplorer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "QuestConqueror",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "JoystickJuggler",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "RetroRover",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "LANPartyLancer",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    },
    {
        name: "GameGuard",
        description: "GIFTING THROUGH UID<br>72 HRS REQUIRED FOR GIFTING",
        image1: "images/p.jpg",
        category: "evt",
        ammount: "4000",
        status: "ava",
        tyepeis: "buy",
        video: "video/x.mp4",
        link: "https://wa.me/918928093361?text=%F0%9F%93%9BBGMI%20POPULARITY%F0%9F%92%A0",
    }
];
